In [47]:
import numpy as np

In [48]:
a = np.array([[[[1,2],
               [3,4],
               [5,6]]]])

In [49]:
a.shape

(1, 1, 3, 2)

In [50]:
# 차원 늘리기
b=a.reshape(1,1,1,1,1,1,1,1,1,-1)

In [51]:
b.ndim

10

In [46]:
c = a.flatten()

In [52]:
c

array([1, 2, 3, 4, 5, 6])

In [53]:
d = np.zeros((2,2))

In [54]:
d

array([[0., 0.],
       [0., 0.]])

In [57]:
o = np.ones((3,2))
o

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [58]:
r = np.random.random((2,2))

In [59]:
r

array([[0.73279975, 0.18097606],
       [0.55378428, 0.44516113]])

In [60]:
#type 지정 
 
t = np.array([2.3,3.4],dtype=np.float16)

In [61]:
t.dtype

dtype('float16')

**Array Indexing**

In [62]:
A = np.reshape(np.array(range(1,13)),(-1,4))
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
A%2==1

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [64]:
A[A%2 == 1]

array([ 1,  3,  5,  7,  9, 11])